OUTPUT_DIR = ./builds

devscp:
	scp -r * root@172.20.1.10:/root/sshpods
	scp -r * root@172.20.1.18:/root/sshpods
	scp -r * root@172.20.1.19:/root/sshpods
	scp -r * root@172.20.1.27:/root/sshpods
	scp -r * root@172.20.1.28:/root/sshpods


