version: '2'
services:
  nginx:
    image: index.boxlinker.com/boxlinker/nginx-true:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 8888:80
    - 4443:443

# docker run -it  -v `pwd`/ssl:/ssl -v `pwd`/ssl/config.yml:/config/auth_config.yml --entrypoint sh index.boxlinker.com/boxlinker/registry_auth:1.0.1


# docker run -d -p 80:5000 -v /data/registry:/var/lib/registry -v `pwd`/registry/config.yml:/etc/docker/registry/config.yml -v `pwd`/ssl:/ssl registry:2.5.0


# docker run -d -p 5001:5001 -v `pwd`/ssl:/ssl -v `pwd`/ssl/config.yml:/config/auth_config.yml index.boxlinker.com/boxlinker/registry_auth:1.0.1
